version: "3.7"
services:
    app:
        container_name: webapp
        restart: always
        build: .
        ports:
            - "8080:8080"
        networks:
            - nodeapp-network
        depends_on: 
            - mongo
    mongo:
        container_name: mongo
        image: mongo
        ports:
            - "27018:27017"
        networks:
            - nodeapp-network

networks:
    nodeapp-network:
        driver: bridge
